import { useEffect, useState } from "react";

import Sidebar from "../components/Sidebar";

import { loadPlans } from "../firebase/plans";

import { auth } from "../firebase/config";

function Plans({ setPage }) {
  const [plans, setPlans] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchPlans() {
      const data = await loadPlans(auth.currentUser.uid);

      setPlans(data);
      setLoading(false);
    }

    fetchPlans();
  }, []);

  return (
    <div className="dashboard">
      <Sidebar setPage={setPage} />

      <main className="main-content">
        <h1>Saved AI Plans 📁</h1>

        <p>Review study plans generated by IPlan.</p>

        {loading ? (
          <p style={{ marginTop: "30px" }}>Loading plans...</p>
        ) : plans.length === 0 ? (
          <div className="subject-card" style={{ marginTop: "30px" }}>
            <p>No saved plans yet.</p>
          </div>
        ) : (
          <div className="quests-grid" style={{ marginTop: "30px" }}>
            {plans.map((plan, index) => (
              <div className="quest-card" key={plan.id || index}>
                <h3>{plan.goal}</h3>

                <p>{plan.hours} hours available</p>

                <ul style={{ marginTop: "10px" }}>
                  {plan.schedule.map((session, sessionIndex) => (
                    <li key={sessionIndex}>{session}</li>
                  ))}
                </ul>

                <p style={{ marginTop: "10px" }}>{plan.advice}</p>
              </div>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}

export default Plans;